### ISSUE TITLE
[Bug] Major issues with Explore and Marketplace buttons

### ISSUE THREAD

**Issue by JunkiEDM** [blakegearin/github-custom-global-navigation#2]
When the Explore or Marketplace buttons are enabled and *not left-aligned*, they act as a clone of the Create button and duplicate the Issues & Pull requests buttons for each:
<details><summary>Screenshot</summary>

Explore + Marketplace - Happy Medium (Custom):
![explore+marketplace-happymedium](https://github.com/blakegearin/github-custom-global-navigation/assets/8350274/bc38f307-b9db-413a-aa8a-767fa0607597)
</details>
<details><summary>DevTools log</summary>

```apl
   GitHub Custom Global Navigation.user.js:957 GitHub Custom Global Navigation: Running
⛔ GitHub Custom Global Navigation.user.js:962 GitHub Custom Global Navigation: Selector '#issues-div' not found
    logError @ GitHub Custom Global Navigation.user.js:962
    cloneAndFlipElements @ GitHub Custom Global Navigation.user.js:1532
    flipIssuesPullRequests @ GitHub Custom Global Navigation.user.js:1612
    updateHeader @ GitHub Custom Global Navigation.user.js:999
    applyCustomizations @ GitHub Custom Global Navigation.user.js:4056
    observeAndModify @ GitHub Custom Global Navigation.user.js:4145
   GitHub Custom Global Navigation.user.js:957 GitHub Custom Global Navigation: Complete
⛔ GitHub Custom Global Navigation.user.js:962 GitHub Custom Global Navigation: Selector '#issues-div' not found
    logError @ GitHub Custom Global Navigation.user.js:962
    cloneAndFlipElements @ GitHub Custom Global Navigation.user.js:1532
    flipIssuesPullRequests @ GitHub Custom Global Navigation.user.js:1612
    updateHeader @ GitHub Custom Global Navigation.user.js:999
    applyCustomizations @ GitHub Custom Global Navigation.user.js:4056
    observeAndModify @ GitHub Custom Global Navigation.user.js:4145
   GitHub Custom Global Navigation.user.js:957 GitHub Custom Global Navigation: Complete
```
Raw log: [github.com-1700691545138.log](https://github.com/blakegearin/github-custom-global-navigation/files/13444898/github.com-1700691545138.log)

</details>

Enabling "Align left" for the button(s) will cause the page to hang for ~10s and make a ton of duplicated elements:
<details><summary>Screenshots</summary>

Explore + Marketplace + Align Left - Happy Medium (Custom):
![explore+marketplace-alignleft-happymedium](https://github.com/blakegearin/github-custom-global-navigation/assets/8350274/2607e235-9f7a-498b-a609-6079ea0f2f36)
Explore + Marketplace + Align Left - Old School (Default):
![explore+marketplace-alignleft-oldschool](https://github.com/blakegearin/github-custom-global-navigation/assets/8350274/b0cf3a91-6e0a-416b-a3df-7410eef050fa)
</details>

- DevTools log (removed childList spam): https://hastebin.skyra.pw/nulosovamo.php
- Raw log: [github.com-1700693391774.log](https://github.com/blakegearin/github-custom-global-navigation/files/13444888/github.com-1700693391774.log)

Tested on:
- Brave Nightly 1.62.73 (Chromium 119.0.6045.163) + Violentmonkey BETA 2.16.1
- Ungoogled Chromium 119.0.6045.159 + Violentmonkey 2.16.0

**Comment by blakegearin** [comment]
Thanks for reporting! I'll take a look.

**Comment by blakegearin** [comment]
Looks like GitHub code changes are responsible for this. For reference, there used to be a `div` wrapper around the `a` and `tool-tip` tags of the Issues and Pull requests links. The removal breaks things. 

I'm working on a fix that also includes some failure checks for better handling. Though worth noting this is enough of a breaking change that it wasn't particularly avoidable, save for not cloning existing elements to create new ones. I've opted for that approach for consistency.

**Comment by blakegearin** [comment]
@JunkiEDM If you'd like to test the fix I've been working on, here's the file: https://github.com/blakegearin/github-custom-global-navigation/blob/fix-2/src/github-custom-global-navigation.user.js

I'll probably merge it in 1-2 days pending your response and some further testing on my end.
