### ISSUE TITLE
[Bug] Rendering errors

### ISSUE THREAD

**Issue by azatoth** [blakegearin/github-custom-global-navigation#3]
**Describe the bug**
Today, I've started to get errors when running this userscript; Both rendering errors and significant slowdowns. I've updated to 1.5.0.

**Screenshots**
![image](https://github.com/blakegearin/github-custom-global-navigation/assets/146477/86067ad5-eba0-4868-bae7-53d6378f4d07)

**Device:**
 - OS: Ubuntu 
 - Browser: Firefox
 - Version: 1.5.0

**Comment by blakegearin** [comment]
Thanks for reporting!

**Comment by blakegearin** [comment]
First of all, thanks for bearing with me on this. I've had a lot going on in my personal life that I needed to prioritize.

As expected, GitHub made some updates that broke things pretty good. I've patched a number of issues I found and put out a `1.5.1` release. Please update and let me know if you continue experiencing issues!

**Comment by azatoth** [comment]
Thanks for the update! And I do understand you have other priorities; personal life takes precedence.

Have tested the new version and it works as expected!
