### ISSUE TITLE
[Bug] Render issue

### ISSUE THREAD

**Issue by terrytw** [blakegearin/github-custom-global-navigation#4]
**Describe the bug**
Please see attached screen shot
![1](https://github.com/blakegearin/github-custom-global-navigation/assets/24227628/393f3a24-0596-4347-9a52-c068252f4492)
![2](https://github.com/blakegearin/github-custom-global-navigation/assets/24227628/f7fded19-f48e-4fe8-bdb4-bac87bbe65bf)
Github would take forever to load, and freezes the browser tab.
Then it loads and it is incorrect.
I believe this happens only in the recent days, because it was OK last week or so. 

**Device (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser chrome 118

**Comment by eshack94** [comment]
I am also experiencing this, since a day ago. GitHub must have changed something on their UI.

**Comment by blakegearin** [comment]
Let's keep discussion over on #3 since it was logged first
